layout:     "main"
logger:     "file"
template:   template_toolkit
gitpath:    "/usr/bin/git"
gitroot:    "/gitroot/perl.git"
datafile:   "~/cherrymaint.db"
lock:       "~/cherrymaint.lock"
# branches : maintenance track name -> range [ start tag, end head ]
branches:
    "maint-5.16":
        - "v5.16.0"
        - blead
    "maint-5.14":
        - "v5.14.0"
        - "maint-5.16"
testing:    0
