layout:     "main"
logger:     "file"
template:   template_toolkit
git:        "/usr/local/bin/git"
gitroot:    "/gitroot/perl.git"
datafile:   "~/cherrymaint.db"
lock:       "~/cherrymaint.lock"
startpoint: "v5.12.0"
endpoint:   blead
